global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "django"
    metrics_path: /metrics
    static_configs:
      - targets: ["web:8000"]

  - job_name: "celery"
    metrics_path: /metrics
    static_configs:
      - targets: ["worker:5555"] # if you expose worker metrics, optional

  - job_name: "rabbitmq"
    metrics_path: /metrics
    static_configs:
      - targets: ["rabbitmq:15672"]
